# Generated by Django 5.2.5 on 2025-08-30 08:32

import blogs.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_prodoctcategory_blogcategory_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(upload_to=blogs.utils.image_upload_blog),
        ),
    ]
