# Generated by Django 5.2.5 on 2025-09-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='blogs.blogcategory', verbose_name='دسته بندی'),
        ),
    ]
