# Generated by Django 5.2.5 on 2025-09-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_blog_category_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(related_name='category', to='blogs.blogcategory', verbose_name='دسته بندی'),
        ),
    ]
